# Generated by Django 4.2.30 on 2026-06-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la classe')),
                ('niveau', models.CharField(blank=True, max_length=50, verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Classe',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='presences.classe')),
            ],
            options={
                'verbose_name': 'Élève',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent'), ('R', 'En retard')], default='P', max_length=1, verbose_name='Statut')),
                ('remarque', models.CharField(blank=True, max_length=200, verbose_name='Remarque')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='presences.eleve')),
            ],
            options={
                'verbose_name': 'Présence',
                'ordering': ['-date', 'eleve__nom'],
                'unique_together': {('eleve', 'date')},
            },
        ),
    ]
